communitiesuk/eip-ero-print-api

.github/workflows/build-and-test.yml, .github/workflows/build-image-and-deploy-to-dev.yml, .github/workflows/deploy-from-version-tag.yml, .github/workflows/deploy-to-int-overnight.yml, .github/workflows/deploy.yml, .github/workflows/files/appspec.yaml, .github/workflows/owasp-dependency-check.yml
This PR adds the github workflows to the print-api
=> EIP1-1925 - Added github workflows

README.md, build.gradle.kts, src/main/kotlin/uk/gov/dluhc/printapi/client/ElectoralRegistrationOfficeManagementApiClient.kt, src/main/kotlin/uk/gov/dluhc/printapi/client/ElectoralRegistrationOfficeManagementApiException.kt, src/main/kotlin/uk/gov/dluhc/printapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/dluhc/printapi/dto/EroManagementApiEroDto.kt, src/main/kotlin/uk/gov/dluhc/printapi/dto/EroManagementApiLocalAuthorityDto.kt, src/main/kotlin/uk/gov/dluhc/printapi/mapper/EroManagementApiEroDtoMapper.kt, src/main/resources/application.yml, src/main/resources/openapi/external/EROManagementAPIs.yaml, src/test/kotlin/uk/gov/dluhc/printapi/client/ElectoralRegistrationOfficeManagementApiClientTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/mapper/EroManagementApiEroDtoMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/EroIdBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/RandomUtils.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/ElectoralRegistrationOfficeResponseBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/LocalAuthorityResponseBuilder.kt, src/test/resources/application-test.yml
This PR is to implement an ero client to acquire ero data from the ero management api for a given gssCode.
=> EIP1-1364: EIP1-2213: Implement ero client to acquire ero data from the ero management api

src/main/kotlin/uk/gov/dluhc/printapi/mapper/PrintDetailsMapper.kt, src/main/kotlin/uk/gov/dluhc/printapi/mapper/SourceTypeMapper.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/IdFactory.kt, src/test/kotlin/uk/gov/dluhc/printapi/mapper/PrintDetailsMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/mapper/SourceTypeMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/IdFactoryTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/RandomUtils.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/dto/EroManagementApiEroDtoBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/dto/EroManagementApiLocalAuthorityDtoBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/PrintDetailsBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/SendApplicationToPrintMessageBuilder.kt
This PR implements the mapper to map SendApplicationToPrintMessage, ero details and localAuthority to PrintDetails.
=> EIP-1364: EIP2132: Implement PrintDetailsMapper

src/main/kotlin/uk/gov/dluhc/printapi/messaging/SendApplicationToPrintMessageListener.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/PrintService.kt, src/test/kotlin/uk/gov/dluhc/printapi/config/IntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/config/WiremockConfiguration.kt, src/test/kotlin/uk/gov/dluhc/printapi/messaging/SendApplicationToPrintMessageListenerIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/IdFactoryTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/WiremockService.kt
This pr is to implement the message listener functionality to save the received message to print-details table.
=> EIP1-1364: EIP1-2135: Persist send application to print message

build.gradle.kts, src/main/kotlin/uk/gov/dluhc/printapi/service/PrintRequestsFileProducer.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/PrintRequestsFileProducerTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/PrintDetailsBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/PrintRequestBuilder.kt
Writes the print requests in a format agreed with the printer to an output stream that will be included in a zip file sent to the printer's SFTP server
=> EIP1-1878 Write print requests to output stream in agreed PSP format

README.md, src/main/kotlin/uk/gov/dluhc/printapi/config/S3Configuration.kt, src/main/kotlin/uk/gov/dluhc/printapi/config/ThreadPoolConfiguration.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/SftpInputStreamProvider.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/ZipOutputStreamProducerRunnable.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/dluhc/printapi/service/SftpInputStreamProviderTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/ZipOutputStreamProducerRunnableTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/zip/FileDetailsBuilder.kt
PR to generate a zip stream containing print requests that are streamed to an SFTP destination.
=> EIP1-1878 Produce zip stream containing print requests

.gitignore, README.md, build.gradle.kts, src/main/kotlin/uk/gov/dluhc/printapi/config/AwsDynamoDbClientConfiguration.kt, src/main/kotlin/uk/gov/dluhc/printapi/config/SchedulerLockConfiguration.kt, src/main/kotlin/uk/gov/dluhc/printapi/jobs/BatchPrintRequestsJob.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/dluhc/printapi/config/LocalStackContainerConfiguration.kt, src/test/resources/application-test.yml
* Schedule locks is temporary disabled
=> EIP1-2214: Implement job scheduler

src/main/kotlin/uk/gov/dluhc/printapi/jobs/ProcessPrintResponsesBatchJob.kt, src/main/kotlin/uk/gov/dluhc/printapi/messaging/models/ProcessPrintBatchStatusUpdateMessage.kt, src/main/resources/openapi/sqs/print-api-sqs-messaging.yaml
=> EIP1-564: EIP1-2261: Schema definition for process print response

src/main/kotlin/uk/gov/dluhc/printapi/database/repository/PrintDetailsRepository.kt, src/main/kotlin/uk/gov/dluhc/printapi/database/repository/PrintDetailsRepositoryException.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/PrintResponseBatchService.kt, src/test/kotlin/uk/gov/dluhc/printapi/database/repository/PrintDetailsRepositoryIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/PrintResponseBatchServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/PrintResponseBuilder.kt
This PR implements a service to process batch responses from the print provider
=> EIP1-2262: EIP1-2418: Implement repository and service to process batch responses

src/main/kotlin/uk/gov/dluhc/printapi/mapper/ProcessPrintResponseMessageMapper.kt, src/main/kotlin/uk/gov/dluhc/printapi/mapper/StatusStepMapper.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/PrintResponseProcessingService.kt, src/test/kotlin/uk/gov/dluhc/printapi/mapper/ProcessPrintResponseMessageMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/mapper/StatusStepMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/PrintResponseProcessingServiceTest.kt
This PR is to implement service method to process batch responses all in one go and queue processing of print responses for all individual print requests.
=> EIP1-2262: EIP1-2420: Process batch responses and queue print responses

src/main/kotlin/uk/gov/dluhc/printapi/rds/entity/Certificate.kt, src/main/kotlin/uk/gov/dluhc/printapi/rds/mapper/CertificateToPrintRequestMapper.kt, src/main/kotlin/uk/gov/dluhc/printapi/rds/mapper/InstantMapper.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/PrintFileDetailsFactory.kt, src/test/kotlin/uk/gov/dluhc/printapi/rds/entity/CertificateTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rds/mapper/CertificateMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rds/mapper/CertificateToPrintRequestMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rds/mapper/InstantMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/PrintFileDetailsFactoryTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/RandomUtils.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/rds/CertificateBuilder.kt
Maps the RDS stored certificate and current print request to the Print Request sent to the printer.
=> EIP1-2386 Map Certificate entity to printer's request

src/test/kotlin/uk/gov/dluhc/printapi/database/entity/CertificateTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/database/repository/CertificateRepositoryIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/jobs/ProcessPrintResponsesBatchJobIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/mapper/CertificateToPrintRequestMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/messaging/ProcessPrintRequestBatchMessageListenerIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/messaging/ProcessPrintResponseMessageListenerIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateBatchingServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/PrintFileDetailsFactoryTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/PrintResponseProcessingServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/PrintServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/ProcessPrintBatchServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/ZipOutputStreamProducerRunnableTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/DeepCopyObjectMapper.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/ObjectExtensions.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/DeepCopyObjectMapper.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/RandomUtils.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/CertificateBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/PrintRequestBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/PrintResponseBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/zip/FileDetailsBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/zip/PhotoLocationBuilder.kt
This PR is to add integration test to cover processing print responses
=> EIP1-2262: EIP1-2509: Add integration tests

src/main/kotlin/uk/gov/dluhc/printapi/rest/CertificateController.kt, src/main/kotlin/uk/gov/dluhc/printapi/rest/CertificateSummaryController.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/GetCertificateSummaryByApplicationIdIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/RandomUtils.kt
This PR is to implement the basic 401, 403 scenarios for the get certificate summary by application id endpoint.
=> EIP1-1990: EIP1-2594: Implement basic get certificate summary by application id endpoint

src/main/kotlin/uk/gov/dluhc/printapi/config/ErrorAttributesConfiguration.kt, src/main/kotlin/uk/gov/dluhc/printapi/exception/GlobalExceptionHandler.kt, src/main/resources/openapi/PrintAPIs.yaml, src/test/kotlin/uk/gov/dluhc/printapi/config/ApiRequestErrorAttributesTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/GetCertificateSummaryByApplicationIdIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/ErrorResponseAssert.kt
This PR is to implement the certificate not found scenario for the certificate summary endpoint
=> EIP1-1990: EIP1-2593: Implement not found scenario for certificate summary endpoint

src/main/kotlin/uk/gov/dluhc/printapi/database/repository/CertificateRepository.kt, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/ddl/0006_add_index_event_date_time_status_to_print_request_status.xml, src/test/kotlin/uk/gov/dluhc/printapi/database/repository/CertificateRepositoryIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/jobs/ProcessPrintResponsesBatchJobIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/RandomUtils.kt
This PR is to implement the repository method to query for daily sent certificates to print provider
=> EIP1-2197: EIP1-2738: Implement repository method to query for daily sent certificates to print provider

src/main/kotlin/uk/gov/dluhc/printapi/service/CertificateBatchingService.kt, src/main/resources/application-dev.yml, src/main/resources/application-int.yml, src/main/resources/application.yml, src/test/kotlin/uk/gov/dluhc/printapi/database/repository/CertificateRepositoryIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateBatchingServiceTest.kt
This PR is to limit the daily certificates sent to print provider.
=> EIP1-2197: EIP1-2739: Limit daily certificates sent to print provider

src/main/resources/openapi/sqs/print-api-sqs-messaging.yaml, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/SendApplicationToPrintMessageBuilder.kt
This PR is to add supporting information format to send application to print sqs message.
=> EIP1-2471: EIP1-2780: Add supporting information format to send application to print message

src/main/resources/openapi/PrintAPIs.yaml
The language of the explainer is selected based on the ERO Nation code included in the gssCode.
=> EIP1-3666 Temporary card explainer document spec

src/main/kotlin/uk/gov/dluhc/printapi/database/entity/TemporaryCertificate.kt, src/main/kotlin/uk/gov/dluhc/printapi/database/entity/TemporaryCertificateStatus.kt, src/main/kotlin/uk/gov/dluhc/printapi/database/repository/TemporaryCertificateRepository.kt, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/ddl/0010_create_temporary_certificate_tables.xml, src/test/kotlin/uk/gov/dluhc/printapi/config/LocalStackContainerConfiguration.kt, src/test/kotlin/uk/gov/dluhc/printapi/config/MySQLContainerConfiguration.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/TestFixedDataFactory.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/TemporaryCertificateBuilder.kt
This PR implements the liquibase DDL, and entity and repository classes for the new tables required for temporary certificates.
=> EIP1-3610 - liquibase DDL & entity classes for temporary certificate tables

src/main/kotlin/uk/gov/dluhc/printapi/dto/CertificateLanguage.kt, src/main/kotlin/uk/gov/dluhc/printapi/dto/GenerateTemporaryCertificateDto.kt, src/main/kotlin/uk/gov/dluhc/printapi/dto/SourceType.kt, src/main/kotlin/uk/gov/dluhc/printapi/exception/GenerateTemporaryCertificateValidationException.kt, src/main/kotlin/uk/gov/dluhc/printapi/exception/GlobalExceptionHandler.kt, src/main/kotlin/uk/gov/dluhc/printapi/mapper/CertificateLanguageMapper.kt, src/main/kotlin/uk/gov/dluhc/printapi/mapper/GenerateTemporaryCertificateMapper.kt, src/main/kotlin/uk/gov/dluhc/printapi/mapper/SourceTypeMapper.kt, src/main/kotlin/uk/gov/dluhc/printapi/rest/TemporaryCertificateController.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/temporarycertificate/TemporaryCertificateService.kt, src/main/kotlin/uk/gov/dluhc/printapi/validator/service/GenerateTemporaryCertificateValidator.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/dluhc/printapi/mapper/CertificateLanguageMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/mapper/GenerateTemporaryCertificateMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/mapper/SourceTypeMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateTemporaryCertificateIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/TestFixedDataFactory.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/dto/GenerateTemporaryCertificateDtoBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/validator/service/GenerateTemporaryCertificateValidatorTest.kt
This PR adds the basic Temporary Certificate Service and a validator to validate the `validOnDate`
Also includes a handful of DTOs and mappers necessary to hook this up
=> EIP1-3439 / EIP1-3722 - Added basic service with business rule validation

src/main/resources/openapi/sqs/print-api-sqs-messaging.yaml
=> NO_JIRA: Updates sqs api with dummy endpoint

src/main/kotlin/uk/gov/dluhc/printapi/config/ExplainerPdfTemplateProperties.kt, src/main/kotlin/uk/gov/dluhc/printapi/config/PdfConfiguration.kt, src/main/kotlin/uk/gov/dluhc/printapi/exception/ExplainerDocumentNotFoundException.kt, src/main/kotlin/uk/gov/dluhc/printapi/exception/GlobalExceptionHandler.kt, src/main/kotlin/uk/gov/dluhc/printapi/exception/TemporaryCertificateExplainerDocumentNotFoundException.kt, src/main/kotlin/uk/gov/dluhc/printapi/rest/AnonymousElectorDocumentController.kt, src/main/kotlin/uk/gov/dluhc/printapi/rest/ControllerSecurityConstants.kt, src/main/kotlin/uk/gov/dluhc/printapi/rest/TemporaryCertificateController.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/pdf/ExplainerPdfService.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/pdf/ExplainerPdfTemplateDetailsFactory.kt, src/main/resources/application.yml, src/main/resources/openapi/PrintAPIs.yaml, src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateAedExplainerDocumentIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/pdf/ExplainerPdfServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/pdf/ExplainerPdfTemplateDetailsFactoryTest.kt
This PR implements the REST API to generate the AED Explainer Document
=> EIP1-3816 / EIP1-3820 - REST API implementation to generate AED Explainer Document

.github/workflows/build-and-push.yml, .github/workflows/build-image-and-deploy-to-dev.yml, .github/workflows/hotfix.yml
- Normal releases now use minor versions (v1.X.0)
- Hotfixes now use patch versions (v1.1.X)
- Changes to hotfix/v* branches (after the initial push) are tagged and deployed to Test.
=> [EIP1-3490] Hotfix build

README.md
=> [EIP1-0000] Important hotfix (urgent)

src/main/kotlin/uk/gov/dluhc/printapi/database/entity/Certificate.kt, src/main/kotlin/uk/gov/dluhc/printapi/database/repository/CertificateRepository.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/CertificateDataRetentionService.kt, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/ddl/0013_initial_retention_data_removed_column.xml, src/test/kotlin/uk/gov/dluhc/printapi/database/repository/CertificateRepositoryIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/jobs/InitialRetentionPeriodDataRemovalJobIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateDataRetentionServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/CertificateAssert.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/CertificateBuilder.kt
Apply new initial retention data removed column to hotfix
=> Feature/EIP1-4053 Add initial retention data removed column (#163)

src/main/kotlin/uk/gov/dluhc/printapi/database/entity/Certificate.kt, src/main/kotlin/uk/gov/dluhc/printapi/database/repository/DeliveryRepository.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/CertificateDataRetentionService.kt, src/main/resources/db/changelog/ddl/0013_initial_retention_data_removed_column.xml, src/test/kotlin/uk/gov/dluhc/printapi/config/IntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/jobs/InitialRetentionPeriodDataRemovalJobIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateDataRetentionServiceTest.kt
Cherry picking commits to hotfix.
=> Feature/v1.0.149.1 EIP1-4053 Ensure all initial retention period data is removed

src/main/resources/openapi/PrintAPIs.yaml
=> EIP1-3229 Add endpoint to return a summary of the Anonymous Elector Documents (AEDs)

src/main/kotlin/uk/gov/dluhc/printapi/rest/AnonymousElectorDocumentController.kt, src/main/resources/openapi/PrintAPIs.yaml, src/test/kotlin/uk/gov/dluhc/printapi/config/IntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/logging/CorrelationIdMdcIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateAedExplainerDocumentIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateAnonymousElectorDocumentIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateTemporaryCertificateExplainerDocumentIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateTemporaryCertificateIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/GetCertificateSummaryByApplicationIdIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/GetTemporaryCertificateSummariesByApplicationIdIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/UpdateAnonymousElectorDocumentStatusIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/JwtAccessTokenBuilder.kt
**Updated to use `certificateNumber`**
=> EIP1-4186: EIP1:4352: API spec for updating AED status

src/main/kotlin/uk/gov/dluhc/printapi/rest/AnonymousElectorDocumentController.kt, src/main/resources/openapi/PrintAPIs.yaml
=> EIP1-3229: EIP1:4572: Updates GET API spec for Getting AEDs with applicationId as queryParam

src/main/kotlin/uk/gov/dluhc/printapi/mapper/AnonymousElectorDocumentMapper.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/aed/AnonymousElectorDocumentService.kt, src/main/resources/openapi/PrintAPIs.yaml, src/test/kotlin/uk/gov/dluhc/printapi/mapper/AnonymousElectorDocumentMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateAnonymousElectorDocumentIntegrationTest.kt
PR to migrate existing data (using liquibase scripts) will follow
=> EIP1-4574: EIP1:4615: Mark AED document as printed upon successful document generation.

src/main/kotlin/uk/gov/dluhc/printapi/database/entity/AnonymousElectorDocumentStatus.kt, src/main/resources/openapi/PrintAPIs.yaml, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/TestFixedDataFactory.kt
=> EIP1-3229: EIP1:4618: api spec for Get AED summaries

src/main/resources/openapi/PrintAPIs.yaml, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/RandomUtils.kt
Loosen validation and allow special characters.
=> EIP1-5091 - Remove formatting rules of electoralRollNumber

src/main/kotlin/uk/gov/dluhc/printapi/dto/SendCertificateNotDeliveredEmailRequest.kt, src/main/kotlin/uk/gov/dluhc/printapi/messaging/service/EmailService.kt, src/main/kotlin/uk/gov/dluhc/printapi/messaging/service/PrintResponseProcessingService.kt, src/test/kotlin/uk/gov/dluhc/printapi/config/IntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/config/LocalStackContainerConfiguration.kt, src/test/kotlin/uk/gov/dluhc/printapi/messaging/ProcessPrintResponseMessageListenerIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/messaging/service/PrintResponseProcessingServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/EmailServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/emails/LocalstackEmailMessageBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/emails/LocalstackEmailMessages.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/emails/LocalstackEmailMessagesClient.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/dto/EroContactDetailsDtoBuilder.kt
This PR adds the logic to trigger the Certificate Not Delivered email
=> EIP1-4998: EIP1-5402: send Certificate Not Delivered email

build.gradle.kts, src/main/resources/application.yml, src/main/resources/logback-spring.xml, src/test/resources/logback-test.xml
This PR implements structured logging using the logstash appender; consistent with how this has already been implemented in the OAVA apps
=> EIP1-5392 - Implemented structured logging with logstash

src/main/resources/openapi/PrintAPIs.yaml
=> EIP1-5620: Api spec for searching AED applications

src/main/kotlin/uk/gov/dluhc/emailnotifications/SesEmailClient.kt
Adds logging to understand who emails are being sent to
=> EIP1-4998 - Add logging for email sending

src/main/kotlin/uk/gov/dluhc/printapi/rest/aed/AedSearchQueryStringParameters.kt, src/main/kotlin/uk/gov/dluhc/printapi/rest/aed/AnonymousElectorDocumentController.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/AedSearchByParametersAreValidConstraintValidatorTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/QueryStringParameterPropertyEditorTest.kt
- Also enabler for next PR for controller changes etc
=> EIP1-5591: EIP1-5754: Validate AED search criteria

src/main/kotlin/uk/gov/dluhc/printapi/rest/aed/AnonymousElectorDocumentController.kt, src/main/resources/openapi/PrintAPIs.yaml
=> EIP1-5853: Api spec update to include pagination while searching AEDs

src/main/kotlin/uk/gov/dluhc/printapi/dto/aed/UpdateAnonymousElectorDocumentDto.kt, src/main/kotlin/uk/gov/dluhc/printapi/exception/GlobalExceptionHandler.kt, src/main/kotlin/uk/gov/dluhc/printapi/exception/UpdateAnonymousElectorDocumentValidationException.kt, src/main/kotlin/uk/gov/dluhc/printapi/mapper/aed/UpdateAnonymousElectorDocumentMapper.kt, src/main/kotlin/uk/gov/dluhc/printapi/rest/aed/AnonymousElectorDocumentController.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/aed/AnonymousElectorDocumentService.kt, src/test/kotlin/uk/gov/dluhc/printapi/mapper/aed/UpdateAnonymousElectorDocumentMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/UpdateAnonymousElectorDocumentByApplicationIdIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/aed/AnonymousElectorDocumentServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/RandomUtils.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/dto/aed/UpdateAnonymousElectorDocumentDtoBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/UpdateAnonymousElectorDocumentRequestBuilder.kt
Currently targeting the branch in my other PR https://github.com/cabinetoffice/eip-ero-print-api/pull/270/files until that's merged.
=> EIP1-5922 - Sad path for update AED contact details

src/main/kotlin/uk/gov/dluhc/printapi/database/mapper/CertificateSummaryDtoMapper.kt, src/main/kotlin/uk/gov/dluhc/printapi/dto/PrintRequestSummaryDto.kt, src/main/kotlin/uk/gov/dluhc/printapi/mapper/CertificateSummaryResponseMapper.kt, src/main/kotlin/uk/gov/dluhc/printapi/mapper/DeliveryAddressTypeMapper.kt, src/main/resources/openapi/PrintAPIs.yaml, src/test/kotlin/uk/gov/dluhc/printapi/database/mapper/CertificateSummaryDtoMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/mapper/CertificateSummaryResponseMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/DeprecatedGetCertificateSummaryByApplicationIdIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/GetCertificateSummaryByApplicationIdIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/TestFixedDataFactory.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/dto/CertificateSummaryDtoBuilder.kt
No thorough review required as this is all deployed already on live and if changes were made then main and eip-main would be slightly out of sync - so more of an FYI.
=> Merge main into eip-main (07/06/23)

src/main/kotlin/uk/gov/dluhc/printapi/database/entity/PrintRequest.kt, src/main/kotlin/uk/gov/dluhc/printapi/database/repository/CertificateSpecificationBuilder.kt, src/main/kotlin/uk/gov/dluhc/printapi/dto/CertificateSearchCriteriaDto.kt, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/ddl/0029_alter_print_request_add_sanitized_surname.xml, src/main/resources/openapi/PrintAPIs.yaml, src/test/kotlin/uk/gov/dluhc/printapi/database/repository/CertificateRepositoryIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/jobs/ProcessPrintResponsesBatchJobIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/SearchCertificateSummariesIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateSummarySearchServiceIntegrationTest.kt
EROPSPT-161 Add searching by surname to search certificates endpoint (#293)
=> Merge main into eip-main

src/main/kotlin/uk/gov/dluhc/printapi/config/S3Configuration.kt, src/main/kotlin/uk/gov/dluhc/printapi/rest/TemporaryCertificateController.kt, src/main/kotlin/uk/gov/dluhc/printapi/rest/aed/AnonymousElectorDocumentPhotoController.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/AedDataRetentionService.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/CertificateDataRetentionService.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/S3AccessService.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/S3Service.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/temporarycertificate/TemporaryCertificateService.kt, src/main/resources/application.yml, src/main/resources/openapi/PrintAPIs.yaml, src/test/kotlin/uk/gov/dluhc/printapi/config/LocalStackContainerConfiguration.kt, src/test/kotlin/uk/gov/dluhc/printapi/jobs/BatchPrintRequestsJobIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/jobs/FinalRetentionPeriodDataRemovalJobIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/messaging/ProcessPrintRequestBatchMessageListenerIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateTemporaryCertificateIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/GenerateAnonymousElectorDocumentIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/GetAnonymousElectorDocumentsPhotoByApplicationIdIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/ReIssueAnonymousElectorDocumentIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/AedDataRetentionServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateDataRetentionServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/S3AccessServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/S3ServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/temporarycertificate/TemporaryCertificateServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/zip/PhotoLocationBuilder.kt, src/test/resources/application-integration-test.yml
I haven't done this in a backwards compatible way as temporary certificates aren't downloaded very often and I'm expecting this all to be released at the same time.
=> EROPSPT-339: Upload temporary certificates to S3

src/main/resources/openapi/PrintAPIs.yaml
Remove references to previous suppliers
=> EROPSPT-369: Remove outdated contact details from API specification

.github/workflows/build-and-push.yml
Correct build and push workflow after SB3 upgrade
https://dluhcdigital.atlassian.net/browse/EIP1-9472
=> EIP1-9472: Correct build and push workflow for SB3

.github/workflows/hotfix.yml
Kirsty's recommended that the "deploy to test" stage be removed, and she's been doing that for some of the other repos.
=> EROPSPT-NONE: Remove deploying to test from hotfix action

src/main/kotlin/uk/gov/dluhc/printapi/database/repository/AnonymousElectorDocumentRepository.kt, src/main/kotlin/uk/gov/dluhc/printapi/mapper/aed/ReIssueAnonymousElectorDocumentMapper.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/AedDataRetentionService.kt, src/test/kotlin/uk/gov/dluhc/printapi/jobs/FinalRetentionPeriodDataRemovalJobIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/mapper/aed/ReIssueAnonymousElectorDocumentMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/ReIssueAnonymousElectorDocumentIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/AedDataRetentionServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/zip/PhotoLocationBuilder.kt
These changes replicate what Kirsty did in #314 but for the final retention period (10 years).
https://mhclgdigital.atlassian.net/browse/EROPSPT-399
=> EROPSPT-399: Reset final remove date when reissuing AED

src/main/kotlin/uk/gov/dluhc/printapi/database/repository/AnonymousElectorDocumentRepository.kt, src/main/kotlin/uk/gov/dluhc/printapi/dto/aed/AnonymousElectorDocumentDto.kt, src/main/kotlin/uk/gov/dluhc/printapi/exception/GlobalExceptionHandler.kt, src/main/kotlin/uk/gov/dluhc/printapi/exception/UpdateAnonymousElectorDocumentAllInitialDataRemovedException.kt, src/main/kotlin/uk/gov/dluhc/printapi/mapper/aed/AnonymousElectorDocumentMapper.kt, src/main/kotlin/uk/gov/dluhc/printapi/mapper/aed/ReIssueAnonymousElectorDocumentMapper.kt, src/main/kotlin/uk/gov/dluhc/printapi/rest/aed/AnonymousElectorDocumentController.kt, src/main/kotlin/uk/gov/dluhc/printapi/rest/aed/AnonymousElectorDocumentPhotoController.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/aed/AnonymousElectorDocumentService.kt, src/main/resources/openapi/PrintAPIs.yaml, src/test/kotlin/uk/gov/dluhc/printapi/mapper/aed/AnonymousElectorDocumentMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/mapper/aed/ReIssueAnonymousElectorDocumentMapperTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/GetAnonymousElectorDocumentsByApplicationIdIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/GetAnonymousElectorDocumentsPhotoByApplicationIdIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/ReIssueAnonymousElectorDocumentIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/UpdateAnonymousElectorDocumentByApplicationIdIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/aed/AnonymousElectorDocumentServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/dto/aed/AnonymousElectorDocumentSummaryDtoBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/AnonymousElectorDocumentBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/AnonymousElectorDocumentBuilder.kt
=> EROPSPT-397: View individual AED with expired certificates and reprint AEDs with expired certificates

src/main/kotlin/uk/gov/dluhc/printapi/database/entity/Certificate.kt, src/main/kotlin/uk/gov/dluhc/printapi/service/PrintFileDetailsFactory.kt, src/test/kotlin/uk/gov/dluhc/printapi/database/entity/CertificateTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/UpdateAnonymousElectorDocumentByApplicationIdIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/PrintFileDetailsFactoryTest.kt
https://mhclgdigital.atlassian.net/browse/EROPSPT-334
=> EROPSPT-334: Only include print requests assigned to batch

src/main/resources/openapi/PrintAPIs.yaml
Need to specify the response type so the data is easier to work and display with in the UI
https://dluhcdigital.atlassian.net/browse/EIP1-11980
=> EIP1-11980-Update explainer doc POST endpoint response type

build.gradle.kts
=> EROPSPT-469: Bump opencsv to patch CVE-2025-48734

build.gradle.kts
=> EROPSPT-489: Upgrade SB and dependencycheck

build.gradle.kts, src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/ReIssueAnonymousElectorDocumentIntegrationTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/service/S3AccessServiceTest.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/AddressAssert.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/AnonymousElectorDocumentDeliveryAssert.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/Assertions.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/CertificateAssert.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/DeliveryAssert.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/ElectoralRegistrationOfficeAssert.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/PrintRequestAssert.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/PrintRequestStatusAssert.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/TemporaryCertificateAssert.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/JwtAccessTokenBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/RandomUtils.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/dto/aed/GenerateAnonymousElectorDocumentDtoBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/CertificateBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/messaging/model/AddressBuilder.kt, src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/GenerateAnonymousElectorDocumentRequestBuilder.kt
- Can leave tags as tbd until merged
=> EROPSPT-503: Address deprecated functions and adopt new default rule for annotation
