communitiesuk/eip-ero-print-api

- build.gradle.kts
- src/main/resources/openapi/sqs/print-api-sqs-messaging.yaml
This PR defines the SQS message `SendApplicationToPrintMessage` (based on `PrintRequestSQS.yaml` from https://github.com/cabinetoffice/eip-ero-print-api/pull/1)
Consistent with how we do this in `notifications-api` the SQS message type definition is in an openAPI spec, but is documented to make it clear it's not a REST API
The standard openAPI codegen that we use in all other projects is used to generate the model classes from it.
Note: I have taken `PrintRequestSQS.yaml` from https://github.com/cabinetoffice/eip-ero-print-api/pull/1 verbatim (well, as close to verbatim as I can whilst converting it to openAPI). I have not renamed, removed or added any fields. Structurally it is the same as proposed in https://github.com/cabinetoffice/eip-ero-print-api/pull/1
This PR is about agreeing and …
> EIP1-1270 - Definition of SQS message SendApplicationToPrintMessage

- src/main/resources/openapi/sqs/print-api-sqs-messaging.yaml
This PR makes a few refinement & corrections to the `SendApplicationToPrintMessage` introduced in my last PR.
Just for context, the `SendApplicationToPrintMessage` is an SQS message that will be consumed by `print-api` (service that owns the queue and therefore the API and this spec); and apps such as VCA (and proxy/postal/overseas as and when we get there) will publish this message. These apps will publish this message to instruct the `print-api` to send the application details to the print provider in order for them to print and post the physical Voter Authority Certificate. Therefore this `SendApplicationToPrintMessage` message needs to contain all the data necessary in order to print the certificate.
The "necessary data" is the data held by VCA (and the other future apps), and is …
> EIP1-1270 - Refining of SQS message SendApplicationToPrintMessage

- src/main/resources/openapi/sqs/print-api-sqs-messaging.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/SendApplicationToPrintMessageBuilder.kt
This PR is to make the middleNames field optional in the SendApplicationToPrintMessage.
> EIP1-1270: EIP1-2177: Make middle names optional in the sqs message

- build.gradle.kts
- src/main/kotlin/uk/gov/dluhc/printapi/service/IdFactory.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/IdFactoryTest.kt
Following the decision in my earlier to PR to use the mongo library and its `ObjectId` class, this PR introduces a simple "ID Factory" that has methods to build a `requestId` (mongo ObjectId), and also a method ready to be implemented to build a VAC Certificate Reference Number (which is essentially an ID, hence its in the ID Factory)
The factory is a bean because it will be injected into the components that use it. I could have opted for a simple file exposing simple functions, but a bean felt better as it will be easier to mock for the purpose of tests (we would have difficulty with assertions if it were a function that could not be mocked); plus the generation of a certificate reference via `certificateReference` is likely to be fairly complex and may involve other collaborators (not …
> EIP1-1364 - Introduction of IdFactory to build requestIds

- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintService.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintServiceTest.kt
This PR implements the `PrintService` with the `savePrintMessage` method to persist the `SendApplicationToPrintMessage` sqs messages into the dynamoDb `print-details` table.
> EIP1-1364: EIP1-2133: Implement PrintService

- src/main/kotlin/uk/gov/dluhc/printapi/config/ClockConfiguration.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/FilenameFactory.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/PhotoLocationFactory.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintFileDetailsFactory.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/FilenameFactoryTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PhotoLocationFactoryTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintFileDetailsFactoryTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/zip/PhotoLocationBuilder.kt
PR to create the file details that includes filename, print requests and photo locations - the `FileDetails` is used in subsequent PR that creates the ZIP output stream.
> EIP1-1878 Add creation of file details

- src/main/kotlin/uk/gov/dluhc/printapi/domain/CertificateNumber.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/IdFactory.kt
- src/test/kotlin/uk/gov/dluhc/printapi/domain/CertificateNumberTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/IdFactoryTest.kt
As discussed in the tech forum just now 😁 I present my finest nerdiness 👍 
This PR adds in a class called `CertificateNumber` that works in a very similar way to `ObjectId` (in that you new one up when you want a new certificate number). Internally it works the same way of holding the value in 12 bytes. The difference is how the 12 byte ID is serialized - `ObjectId` serializes as 24 hex chars. `CertificateNumber` serializes as 20 characters from its own alphabet
> EIP1-2131 - Addition of CertificateNumber

- build.gradle.kts
- owasp.suppressions.xml
Version bumps to fix OWASP dependency report issues
`print-api` is now down to just 1 reported vulnerability (kapt related) 🎉 
The version bump to Spring Security is important - we need to roll that out into all our other apps
> NO-JIRA - Version bumps to fix OWASP dependency report issues

- build.gradle.kts
- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintRequestsFileProducer.kt
- src/main/resources/yamlschema/BatchResponse.yaml
- src/main/resources/yamlschema/PrintRequest.yaml
- src/main/resources/yamlschema/PrintResponse.yaml
- src/main/resources/yamlschema/PrintResponses.yaml
- src/main/resources/yamlschema/README.md
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/PrintDetailsToPrintRequestMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintRequestsFileProducerTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/PrintRequestBuilder.kt
The PR fixes the Print Provider API spec (yamlschema) and our codegen from it. Specifically it:
* Corrects `requestId` to not be a UUID in the `PrintResponse` object (its a 24 char hex string instead)
* Adds some examples and descriptions
* Adds config to our codegen so that date and datetime fields get generated using java8 classes rather than `java.util.Date` for date fields, and `String` (!!!) for `date-time` fields.
In respect of the contract between EROP and the Print Provider the only thing that has changed is the data type for `requestId` in `PrintResponse`
> EIP1-385 - correct `requestId` data type in yamlschema; codegen to use java8 dates

- src/main/kotlin/uk/gov/dluhc/printapi/mapper/ElectoralRegistrationOfficeMapper.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/PrintDetailsMapper.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/ElectoralRegistrationOfficeMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/PrintDetailsMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/messaging/SendApplicationToPrintMessageListenerIntegrationTest.kt
This PR fixes the mapping of the ERO fields in the `PrintRequest` entity.
At the moment the fields that were missing (ERO phone number, email address, website, address street and address postcode) are mapped to empty string as we don't have the final values yet. This will be updated in a future PR
> EIP1-1878 - Fix mapping of ERO fields in print request entity

- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/PrintDetails.kt
- src/main/resources/openapi/sqs/print-api-sqs-messaging.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/PrintDetailsMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/messaging/SendApplicationToPrintMessageListenerIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/SendApplicationToPrintMessageBuilder.kt
Future stories will expose REST APIs on the print-api that need to return data about the print request (VAC Certificate). The data that these REST APIs need to return include attributes relating to the Voter Card Application as well as the certificate print request.
A previous PR added `applicationReceivedDateTime` and `deliveryMethod` to the SQS message which VCA will need to send to this API. This PR adds the ID of the user that is requesting the print.
Corresponds to https://github.com/cabinetoffice/eip-ero-voter-card-applications-api/pull/272
> EIP1-2413 Add userId to SendApplicationToPrintMessage

- README.md
- src/main/kotlin/uk/gov/dluhc/printapi/config/MessagingConfiguration.kt
- src/main/kotlin/uk/gov/dluhc/printapi/messaging/ProcessPrintResponseMessageListener.kt
- src/main/resources/application.yml
- src/main/resources/openapi/sqs/print-api-sqs-messaging.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/config/IntegrationTest.kt
- src/test/resources/application-test.yml
This PR is an enabler for the real work thats being done in EIP1-2262
It:
* adds a new message type `ProcessPrintResponseMessage` to the SQS schema and codegens it
* adds a new queue bean for the new type, so that messages can be sent to it (future work in 2262)
* adds a new listener for the new type, so that messages can be consumed (future work on 2262)
* documents the environment variable required for the queue name
The corresponding infra changes (create the queue, wire the env var into the container) have already been done and merged
Next tasks after this are to:
* Add the updated SQS schema to VCA (even though VCA wont be publishing or consuming messages of this type)
* Add the queue and env var to our docker-compose setup
> EIP1-2262 - Added queue and basic listener for processing print response message

- src/main/kotlin/uk/gov/dluhc/printapi/jobs/ProcessPrintResponsesBatchJob.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintResponseFileReadinessService.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/SftpService.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintResponseFileReadinessServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/SftpServiceTest.kt
We want the ability to **continue processing** rest of the batch files, when any operation on one of the files fails.
- Also introduced `PrintResponseFileReadinessService` that takes the weight off from the `ProcessPrintResponsesBatchJob`
> EIP1-564: EIP1:2369: Continue processing rest of the batch files on any file failure

- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintRequestsService.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintRequestsServiceTest.kt
This PR changes how the ASSIGNED_TO_BATCH status is set on a PrintDetails entity when it is assigned to batch
The problem was we were not setting the `eventDateTime` field when adding the status. I have simplified (IMHO) the code to move away from a functional approach, and change to mutating the PrintDetails via its addStatus method
(I know, I know! immutability rocks, but the functional approach was making it hard in this case to grok and do what we needed to do)
> EIP1-1878 - Fixes how the ASSIGNED_TO_BATCH status is set

- src/main/kotlin/uk/gov/dluhc/printapi/database/repository/PrintDetailsRepository.kt
- src/main/kotlin/uk/gov/dluhc/printapi/rds/entity/Certificate.kt
- src/main/kotlin/uk/gov/dluhc/printapi/rds/entity/PrintRequestStatus.kt
- src/main/kotlin/uk/gov/dluhc/printapi/rds/repository/CertificateRepository.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintFileDetailsFactory.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintRequestsService.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintService.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/ProcessPrintBatchService.kt
- src/test/kotlin/uk/gov/dluhc/printapi/messaging/ProcessPrintRequestBatchMessageListenerIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rds/entity/CertificateTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rds/mapper/CertificateMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rds/mapper/CertificateToPrintRequestMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rds/mapper/InstantMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rds/repository/CertificateRepositoryTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintRequestsServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/ProcessPrintBatchServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/CertificateDeliveryBuilder.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/PrintDetailsBuilder.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/rds/CertificateBuilder.kt
Introduced MySQL alongside the existing DynamoDB for saving a print request to the database and then using that when processing to write printer's request files.  Later the DynamoDB code will be removed once the response processing is updated to use the MySQL database.
Note that the MySQL processing is being added alongside the existing DynamoDB at this stage (response file processing still needs updating - in next PR).  At this stage:
- 1 application is saved in both DynamoDB and MySQL
- Create separate batches for Dynamo and MySQL and raise SQS for all batches
- Processing has 1 listener that skips creating zips for MySQL but updates its status
Next steps:
Update response file processing 
Switch off DynamoDB
> EIP1-2386 Integrate MySQL in process to send printer zip file or print requests

- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintResponseProcessingService.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/ProcessPrintBatchService.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintResponseProcessingServiceTest.kt
Adds processing of response file using the MySQL database records.
Subsequent PR will remove the Dynamo interactions.
> EIP1-2386 Process batch responses file with MySQL

- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintResponseFileService.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintResponseProcessingService.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintResponseFileServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintResponseProcessingServiceTest.kt
DynamoDB updates were being done inside the method and then SQS messages sent, with MySQL and the `@Transaction` annotation the semantics had changed so SQS messages were sent before the database updates were made.  Refactored for database updates to happen before SQS messages are sent.
> EIP1-2386 Refactor to flush database updates before SQS messages are sent.

- src/main/kotlin/uk/gov/dluhc/printapi/jobs/ProcessPrintResponsesBatchJob.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintRequestsService.kt
- src/main/resources/application-dev.yml
This PR changes the cron times in `dev` for both cron jobs to every 10 minutes
Plus removes the logging from the `ProcessPrintResponsesBatchJob` (because the service method that it calls also logs, so this was pure noise)
I've also added logging to the service class that the batch cron job calls so that we can see when it is invoked etc.
> EIP1-1878 - Logging in scheduled services; adjusted cron times in dev

- src/main/kotlin/uk/gov/dluhc/printapi/exception/EmptyBatchException.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/CertificateBatchingService.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintRequestsService.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/ProcessPrintBatchService.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateBatchingServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintRequestsServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/ProcessPrintBatchServiceTest.kt
Batches need to be saved to database before SQS messages related to the batches are queued.  Attempting to process a print batch containing no certificates should result in an error so SQS message is retried in a race-condition.
> EIP1-2386 Persist print request batches before sending SQS messages and reject empty batches

- src/main/kotlin/uk/gov/dluhc/printapi/config/CorrelationIdMdcConfiguration.kt
- src/main/kotlin/uk/gov/dluhc/printapi/config/WebMvcConfig.kt
- src/main/kotlin/uk/gov/dluhc/printapi/messaging/MessageQueue.kt
- src/main/resources/application.yml
- src/test/resources/logback-test.xml
This PR adds a correlation ID to all log messages using an MCD variable, Interceptors and some AOP
I've tried to think about this in a generic way so that it could be added to all of our apps, and it would "just work" .... 🤔
So, my thinking is that there are 3 "starting" points for our apps:
* an incoming HTTP request ie. a REST API
* a consumed (received) SQS message
* a scheduled task (@Scheduler)
for each of these 3 "starting" points we can use an Interceptor (http requests) or AOP (SQS and scheduled tasks) to generate a correlation ID and add it to MDC. We can then include the MDC variable in the log pattern. Simple stuff
But, we also want to be able to pass around / maintain a correlation ID across threads, and even across apps.
So, the Interceptor (http requests) and AOP (SQS) need …
> EIP1-1878 - logging with correlationId

- src/main/kotlin/uk/gov/dluhc/printapi/mapper/CertificateToPrintRequestMapper.kt
- src/main/resources/yamlschema/BatchResponse.yaml
- src/main/resources/yamlschema/PrintRequest.yaml
- src/main/resources/yamlschema/PrintResponse.yaml
- src/main/resources/yamlschema/PrintResponses.yaml
- src/main/resources/yamlschema/README.md
This PR updates the `certificateFormat` enum as used in `PrintRequest` in the Print Provider schema; by renaming `largeprint` to `large-print` and `audio` to `easy-read`. This change is as per agreement with the Print Provider
Things to note:
* The field and enum is still called `certificateFormat` even though it is **not** the certificate format, and is in fact the format of the supporting information that is sent with the certificate.
* I was not able to negotiate changing the field name itself as the Print Provider have already developed to the existing spec and are not open to that degree of refactoring.
* I have updated the `description` attribute to make this as clear as possible
* I have up'versioned the spec; but also changed to semantic versioning with `1.0.0` being this version. …
> EIP1-2471 - Update Print Provider schema `certificateFormat` enum

- src/main/kotlin/uk/gov/dluhc/printapi/config/JacksonConfiguration.kt
- src/main/resources/openapi/sqs/print-api-sqs-messaging.yaml
This PR is to add the supporting information format to `SendApplicationToPrintMessage`, so the value can be received from VCA and later persisted and sent to print provider in the agreed format.
> EIP1-2471: EIP1-2780: Add supportingInformationFormat to SendApplicationToPrintMessage

- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/SupportingInformationFormat.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/CertificateLanguageMapper.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/CertificateToPrintRequestMapper.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/SupportingInformationFormatMapper.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/CertificateLanguageMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/CertificateToPrintRequestMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/SupportingInformationFormatMapperTest.kt
This PR maps the Supporting Information Format field from the Print Request entity into the Print Request model object (PSV)
It also maps the certificate language (not entirely sure how "create and send batch files" was system tested and integration tested without this ?? I know the integration testing was supposed to be looking at certificate language! 🤷‍♂️ )
> EIP1-2471 - Map the supporting information format into Print Request

- build.gradle.kts
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/PrintRequestMapper.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/SupportingInformationFormatMapper.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/CertificateMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/PrintRequestMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/SupportingInformationFormatMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/messaging/SendApplicationToPrintMessageListenerIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/dto/EroContactDetailsExtensions.kt
This PR is to map the supporting information format in the `SendApplicationToPrintMessage` model to db entity to persist that value.
> EIP1-2471: EIP1-2782: Map supporting information format to db entity

- src/main/resources/application-int.yml
This PR removes the additional logging for the SFTP components that we put into `int` recently.
> EIP1-1878 - Turn down SFTP logging on int

- src/main/kotlin/uk/gov/dluhc/printapi/service/CertificateBatchingService.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/dluhc/printapi/logging/CorrelationIdMdcIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateBatchingServiceTest.kt
This PR implements a suggestion from @adacayi to improve the efficiency of assigning batch IDs to Print Requests
Previously we looped through the batch (up to 50 records in a batch) and called `.save` on the repository for each record.
Now we call `saveAll` on the collection, therefore saving up to 50 records at a time.
IE. previously, if there were 190 Print Requests that we had grouped into 4 batches (50, 50, 50, 40); we would call `.save` 190 times.
Now with this change the same 190 Print Requests groups into the same 4 batches will results in 4 calls to `.saveAll` (50, 50, 50, 40)
This should be a massive improvement when dealing with very large numbers of un-batched Print Requests, as per the problem described in EIP1-2885
> EIP1-2885 - Improve efficiency of assigning batch ids to certificates

- src/main/kotlin/uk/gov/dluhc/printapi/database/repository/CertificateRepository.kt
- src/main/kotlin/uk/gov/dluhc/printapi/jobs/BatchPrintRequestsJob.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/CertificateBatchingService.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintRequestsService.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/dluhc/printapi/database/repository/CertificateRepositoryIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateBatchingServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintRequestsServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/CertificateBuilder.kt
This PR sets a limit to the number of un-batched Print Requests that the batch job will pull from the database at a time (to prevent very very long running processes that span several cron invocations as described in EIP1-2885)
The limit is set at 5,000 in `application.yml` as proposed in EIP1-2885
> EIP1-2885 - Set batch job limit

- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/Certificate.kt
- src/main/kotlin/uk/gov/dluhc/printapi/database/repository/CertificateRepository.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/CertificateBatchingService.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/FilenameFactory.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintFileDetailsFactory.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintResponseProcessingService.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/ProcessPrintBatchService.kt
- src/test/kotlin/uk/gov/dluhc/printapi/database/entity/CertificateTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/database/repository/CertificateRepositoryIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/messaging/SendApplicationToPrintMessageListenerIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateBatchingServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/FilenameFactoryTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintFileDetailsFactoryTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintResponseProcessingServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/ProcessPrintBatchServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/RandomUtils.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/CertificateBuilder.kt
Original implementation had data structure to support multiple print requests per Certificate but the code was simplified to act against the current (only) print request in the various flows.  This PR updates the codebase to select the relevant Print Request based on one of its status, its assigned batch or its request id.  Refactored `getCurrentPrintRequest()` to be private in the Certificate.
> EIP1-2467 Refactor to support certificates with several print requests

- .github/workflows/build-image-and-deploy-to-dev.yml
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/EroDtoMapper.kt
- src/main/resources/openapi/external/EROManagementAPIs.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/messaging/SendApplicationToPrintMessageListenerIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/LocalAuthorityResponseBuilder.kt
This PR fixes bug EIP1-3454 by bringing in the latest ERO Management openApi spec (v1.2.1) which introduces a new `name` field on the `contactDetails` object in the REST API response from ERO Management. The new `name` field is then mapped to the `issuingAuthority` and `issuingAuthorityCy` fields in the `Certificate` entity.
The rest of the code required for this overall bugfix is already there and was committed in my last PR for this.
> Bugfix EIP1-3454 - use new ero management API

- src/main/resources/openapi/PrintAPIs.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/config/LocalStackContainerConfiguration.kt
- src/test/kotlin/uk/gov/dluhc/printapi/config/MySQLContainerConfiguration.kt
This PR updates the openAPI spec with the new endpoint for generating a temporary certificate
(it also updates the TestContainer names based on a request from @abdullah-sanver-valtech that I saw after I'd merged my last PR)
> EIP1-3439 / EIP1-3721 - openAPI spec for generating a temporary certificate

- src/main/kotlin/uk/gov/dluhc/printapi/rest/CertificateSummaryController.kt
- src/main/kotlin/uk/gov/dluhc/printapi/rest/ControllerSecurityConstants.kt
- src/main/kotlin/uk/gov/dluhc/printapi/rest/TemporaryCertificateController.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateTemporaryCertificateIntegrationTest.kt
This PR introduces the basic skeleton controller for Temporary Certificates with the standard 401/403 scenarios
> EIP1-3722 - Basic controller with 401/403 scenarios

- src/main/kotlin/uk/gov/dluhc/printapi/client/ElectoralRegistrationOfficeManagementApiClient.kt
- src/main/kotlin/uk/gov/dluhc/printapi/dto/EroDto.kt
- src/main/kotlin/uk/gov/dluhc/printapi/exception/TemporaryCertificateExplainerDocumentNotFoundException.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/EroDtoMapper.kt
- src/main/kotlin/uk/gov/dluhc/printapi/rest/TemporaryCertificateController.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/temporarycertificate/ExplainerPdfService.kt
- src/test/kotlin/uk/gov/dluhc/printapi/client/ElectoralRegistrationOfficeManagementApiClientTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/EroDtoMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateTemporaryCertificateExplainerDocumentIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/temporarycertificate/ExplainerPdfServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/dto/EroDtoBuilder.kt
Reject requests to create an explainer document when the ERO identified by the provided GSS Code does not match the ERO ID included in the request.
> EIP1-3666 Validate the ERO found by GSS Code matches the ERO from the URL when generating temporary certificate explainer PDF

- src/main/kotlin/uk/gov/dluhc/printapi/validator/service/GenerateTemporaryCertificateValidator.kt
- src/test/kotlin/uk/gov/dluhc/printapi/validator/service/GenerateTemporaryCertificateValidatorTest.kt
This PR corrects/clarifies the validation message for when the `validOnDate` is too far in the future
IE. The following:
```
{
"timestamp": "2023-02-07T10:41:26.155Z",
"status": 400,
"error": "Bad Request",
"message": "Temporary Certificate validOnDate cannot be greater than 30 in the future (cannot be after 2023-03-09)"
}
```
becomes:
```
{
"timestamp": "2023-02-07T10:41:26.155Z",
"status": 400,
"error": "Bad Request",
"message": "Temporary Certificate validOnDate cannot be greater than 30 calendar days in the future (cannot be after 2023-03-09)"
}
```
> EIP1-3439 / EIP1-3722 - Corrected validation message

- src/main/kotlin/uk/gov/dluhc/printapi/database/mapper/CertificateSummaryDtoMapper.kt
- src/test/kotlin/uk/gov/dluhc/printapi/database/mapper/CertificateSummaryDtoMapperTest.kt
This PR sorts the `printRequestSummaries` collection in the `CertificateSummaryResponse` by the event datetime
This is to make it easier for the UI to render the response
> EIP1-1990 - Sort print requests in collection

- src/main/kotlin/uk/gov/dluhc/printapi/client/BankHolidayDataClient.kt
- src/main/kotlin/uk/gov/dluhc/printapi/client/BankHolidayDataFileClient.kt
- src/main/kotlin/uk/gov/dluhc/printapi/config/DataRetentionConfiguration.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/CertificateRemovalDateResolver.kt
- src/main/resources/application.yml
- src/main/resources/bank-holidays.json
- src/test/kotlin/uk/gov/dluhc/printapi/client/BankHolidayDataFileClientTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/config/IntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateRemovalDateResolverTest.kt
We've recently discovered we need to remove the address and addressee fields that are stored against each certificate's print requests much sooner than anticipated. Since this data is not on the printed certificate itself, we need to remove it 28 working days after a certificate is "issued" (as opposed to 28 working days following approval for the application's data in VCA).
There is currently some debate re what the "issue" date is exactly, but that is outside the focus of this PR.
> EIP1-3802 - Calculate certificate delivery info removal date

- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/Certificate.kt
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/ddl/0011_initial_data_retention_period_changes.xml
This PR is an enabler to allow us to store the date for removing PII data which is not on the printed certificate itself (currently just the addressee/address on the envelope).
> EIP1-3800 - Liquibase/entity changes for the initial data retention period

- src/main/kotlin/uk/gov/dluhc/printapi/rest/TemporaryCertificateController.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/PhotoLocationFactory.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/S3ArnParser.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/temporarycertificate/CertificatePdfTemplateDetailsFactory.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/temporarycertificate/PdfFactory.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/temporarycertificate/TemporaryCertificateService.kt
- src/test/kotlin/uk/gov/dluhc/printapi/config/IntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateTemporaryCertificateExplainerDocumentIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateTemporaryCertificateIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/S3ArnParserKtTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/temporarycertificate/CertificatePdfTemplateDetailsFactoryTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/temporarycertificate/TemporaryCertificateServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/zip/PhotoLocationBuilder.kt
Updates the Controller and Integration tests for generation of the PDF temporary certificate - includes additional request validation in the service that the GSS code included in the request finds an ERO that the user is allowed access.
> EIP1-3439 Add to controller endpoint the functionality to create a temporary certificate PDF file

- src/main/resources/openapi/PrintAPIs.yaml
This PR adds the new API spec for the REST API to get the Temporary Certificate summaries for an application
> EIP1-511 - openAPI doc for endpoint to get Temporary Certificates for an application

- src/main/kotlin/uk/gov/dluhc/printapi/rest/TemporaryCertificateController.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/ControllerSpringSecurityIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateTemporaryCertificateExplainerDocumentIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateTemporaryCertificateIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GetCertificateSummaryByApplicationIdIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GetTemporaryCertificateSummariesByApplicationIdIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/SpringSecurityIntegrationTest.kt
This PR adds the basic controller for the new endpoint to get the Temporary Certificate Summaries for the application; complete with our usual 401/403 scenarios.
> EIP1-511 - Basic controller with 401/403 scenarios

- src/main/kotlin/uk/gov/dluhc/printapi/config/TemporaryCertificateExplainerPdfTemplateProperties.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/temporarycertificate/ExplainerPdfTemplateDetailsFactory.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/dluhc/printapi/service/temporarycertificate/ExplainerPdfTemplateDetailsFactoryTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/dto/EroContactDetailsDtoBuilder.kt
Refactor the temporary certificate placeholder properties to dynamically assign values to appropriate placeholder to avoid leaving blank fields for optional data.
> EIP1-3946 Refactor the temporary certificate placeholder properties

- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/TemporaryCertificate.kt
- src/main/kotlin/uk/gov/dluhc/printapi/dto/TemporaryCertificateStatusDto.kt
- src/main/kotlin/uk/gov/dluhc/printapi/dto/TemporaryCertificateSummaryDto.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/TemporaryCertificateSummaryMapper.kt
- src/main/kotlin/uk/gov/dluhc/printapi/rest/TemporaryCertificateController.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/temporarycertificate/TemporaryCertificateFinderService.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/temporarycertificate/TemporaryCertificateSummaryService.kt
- src/main/resources/openapi/PrintAPIs.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/TemporaryCertificateSummaryMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GetTemporaryCertificateSummariesByApplicationIdIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/temporarycertificate/TemporaryCertificateFinderServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/temporarycertificate/TemporaryCertificateSummaryServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/RandomUtils.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/dto/TemporaryCertificateSummaryBuilder.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/TemporaryCertificateBuilder.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/TemporaryCertificateSummaryBuilder.kt
This PR implements the main controller method, through service, through repository; to implement the happy path for the REST API to get Temporary Certificate Summaries for a given application
> EIP1-511 - Implemented controller through to service and repository

- src/main/kotlin/uk/gov/dluhc/printapi/rest/TemporaryCertificateController.kt
- src/main/resources/openapi/PrintAPIs.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateTemporaryCertificateExplainerDocumentIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateTemporaryCertificateIntegrationTest.kt
This PR defines the open API spec definition for the endpoint to generate the explainer document for an AED
As per [this slack conversation](https://valtechhub.slack.com/archives/C03TZSU0H8Q/p1676390742170609), I have also changed the path of the existing Temporary Certificate endpoints to be consistent with our standard and patterns (plural nouns), and updated the tags
> EIP1-3816 / EIP1-3817 - Added AED explainer doc API to open API spec

- README.md
- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/Certificate.kt
- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/PrintRequest.kt
- src/main/kotlin/uk/gov/dluhc/printapi/database/repository/CertificateRepository.kt
- src/main/kotlin/uk/gov/dluhc/printapi/jobs/BatchPrintRequestsJob.kt
- src/main/kotlin/uk/gov/dluhc/printapi/jobs/InitialRetentionPeriodDataRemovalJob.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/CertificateDataRetentionService.kt
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/ddl/0012_supporting_information_non_mandatory.xml
- src/test/kotlin/uk/gov/dluhc/printapi/config/IntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/jobs/InitialRetentionPeriodDataRemovalJobIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/messaging/ApplicationRemovedMessageListenerTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateDataRetentionServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/CertificateAssert.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/PrintRequestAssert.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/CertificateBuilder.kt
This PR implements a scheduled task to remove specific data that needs to be removed from a certificate after the first (initial) retention period has ended.
This was supposed to be a simple task, but has ended up being more complicated due to going round in circles over the definition of the retention policy and establishing exactly which data needs to be removed!
> EIP1-3803 - Job to remove initial retention period data for VCAs

- src/main/kotlin/uk/gov/dluhc/printapi/exception/EmptyBatchException.kt
- src/main/kotlin/uk/gov/dluhc/printapi/exception/InsufficientPrintRequestsInBatchException.kt
- src/main/kotlin/uk/gov/dluhc/printapi/messaging/ProcessPrintRequestBatchMessageListener.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/CertificateBatchingService.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/FilenameFactory.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintRequestCounter.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintRequestsService.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/ProcessPrintBatchService.kt
- src/main/resources/openapi/sqs/print-api-sqs-messaging.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/logging/CorrelationIdMdcIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateBatchingServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintRequestCounterTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintRequestsServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/ProcessPrintBatchServiceTest.kt
Occasionally print requests that have been assigned to a batch are never sent to the print provider.  Either the SQS message is never processed successfully and ends on the DLQ or it is processed but misses some of the print requests included in the batch.  To tighten the processing the SQS message includes a count of the print requests in the batch.  When processing the SQS message the processing verifies that the expected number of print requests is loaded from the database.
> EIP1-3765 Include the number of print requests with batch id for processing to prevent part processing batches

- README.md
- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/Certificate.kt
- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/PrintRequest.kt
- src/main/kotlin/uk/gov/dluhc/printapi/database/repository/CertificateRepository.kt
- src/main/kotlin/uk/gov/dluhc/printapi/jobs/BatchPrintRequestsJob.kt
- src/main/kotlin/uk/gov/dluhc/printapi/jobs/InitialRetentionPeriodDataRemovalJob.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/CertificateDataRetentionService.kt
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/ddl/0012_supporting_information_non_mandatory.xml
- src/test/kotlin/uk/gov/dluhc/printapi/config/IntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/jobs/InitialRetentionPeriodDataRemovalJobIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/messaging/ApplicationRemovedMessageListenerTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateDataRetentionServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/CertificateAssert.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/PrintRequestAssert.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/CertificateBuilder.kt
This PR cherry picks these merge commits which were made since the release last Wednesday:
* https://github.com/cabinetoffice/eip-ero-print-api/commit/7e6fdf6fd797ebb73f7286533492a0f53bfb08b7
* https://github.com/cabinetoffice/eip-ero-print-api/commit/c8162ca85d2137640a595cc77f6106fc49da23bd
This enables the removal of the initial retention period data.
> Feature/EIP1-3724 - hotfix v1.0.149 - Enable data removal job in prod

- src/main/resources/openapi/PrintAPIs.yaml
Endpoint to call that creates a PDF document for the Anonymous Elector Document - expect this endpoint to be called from VCA.  Later requirements for reprinting due to a LSD document or after a new electoral roll number is assigned to the elector will use a different endpoint.
> EIP1-3824 Add endpoint to generate Anonymous Elector Document (AED)

- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/Certificate.kt
- src/main/kotlin/uk/gov/dluhc/printapi/database/repository/DeliveryRepository.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/CertificateDataRetentionService.kt
- src/test/kotlin/uk/gov/dluhc/printapi/config/IntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/jobs/InitialRetentionPeriodDataRemovalJobIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateDataRetentionServiceTest.kt
More in-depth testing has revealed it's not enough just to set various values to `null` and then call `save()` on the `CertificateRepository`. That's not has how `CascadeType.ALL` works and is something I was always unsure about (I know, I should have tested this more thoroughly to begin with but haste got the better of me! 🙄 ).
Instead I've reluctantly introduced `DeliveryRepository` so I can call `delete()` on each one. This subsequently removes all child `address` entities as well (i.e. exactly how `CascadeType.ALL` is intended to work).
> EIP1-4053 - Add DeliveryRepository to ensure Delivery data is removed

- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintRequestCounter.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintRequestCounterTest.kt
Found issue with the number of requests being included in the SQS message being more than it should as double counting print requests.
> EIP1-3765 Remove duplicate print requests from count

- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/AedPrintRequest.kt
- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/AnonymousElectorDocument.kt
- src/main/kotlin/uk/gov/dluhc/printapi/dto/GenerateAnonymousElectorDocumentDto.kt
- src/main/kotlin/uk/gov/dluhc/printapi/exception/GlobalExceptionHandler.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/AnonymousElectorDocumentMapper.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/GenerateAnonymousElectorDocumentMapper.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/SupportingInformationFormatMapper.kt
- src/main/kotlin/uk/gov/dluhc/printapi/rest/AnonymousElectorDocumentController.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/aed/AedPdfTemplateDetailsFactory.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/aed/AnonymousElectorDocumentService.kt
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/ddl/0014_create_anonymous_elector_document_tables.xml
- src/main/resources/openapi/PrintAPIs.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/config/IntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/AnonymousElectorDocumentMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/GenerateAnonymousElectorDocumentMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/SupportingInformationFormatMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateAnonymousElectorDocumentIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/aed/AnonymousElectorDocumentServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/GenerateAnonymousElectorDocumentRequestBuilder.kt
Example AED
Mainly the mapper from REST API to DTO, Controller Method and Integration Test with few minor fixes and updates.
> EIP1-3823 Add secure endpoint to generate an Anonymous Elector Document (AED)

- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/AnonymousElectorDocument.kt
- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/Certificate.kt
- src/main/kotlin/uk/gov/dluhc/printapi/database/repository/AnonymousElectorDocumentRepository.kt
- src/main/kotlin/uk/gov/dluhc/printapi/database/repository/CertificateRepository.kt
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/ddl/0016_final_retention_data_removed_column.xml
- src/test/kotlin/uk/gov/dluhc/printapi/database/repository/AnonymousElectorDocumentRepositoryIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/database/repository/CertificateRepositoryIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/AnonymousElectorDocumentBuilder.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/CertificateBuilder.kt
This PR adds `finalRetentionRemovalDate` to the `Certificate` entity, so that we can set the date when any remaining certificate data should be removed.
Whilst in the area, I spotted that `AnonymousElectorDocument` was missing `initialRetentionDataRemoved`, which I had to add to `Certificate` retrospectively (presumably after @Neil-Massey initially created the AED entity), so I've included that here. It then seemed unreasonable not to add `finalRetentionRemovalDate` as well, even though both these columns are strictly part of [EIP1-3753](https://technologyprogramme.atlassian.net/browse/EIP1-3753) and [EIP1-3567](https://technologyprogramme.atlassian.net/browse/EIP1-3567) respectively.
> EIP1-4154 - Retention period columns

- src/main/kotlin/uk/gov/dluhc/printapi/service/CertificateRemovalDateResolver.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateRemovalDateResolverTest.kt
This PR covers the somewhat quirky requirement that any remaining Certificate/AED data should be removed on the "tenth 1st July" from the issue date.
> EIP1-4156 - Calculate final retention period removal date for Elector Documents

- src/main/kotlin/uk/gov/dluhc/printapi/config/SftpConfiguration.kt
Identified issue with the Integrity SFTP server where connections were going stale and requests to their server were failing with IOExceptions.  The timeout of sessions on the Integrity server is 1 hour, with the A1 Printer having a 2 minute timeout.  As the frequency of connections is low, with the Zip writing scheduled to run at a maximum of once every 5 minutes and the Response file processing every 30 minutes it is thought that sessions in the SFTP cache are going stale between requests on the Integrity server.  As the interactions between the Print API and SFTP servers is infrequent the caching is being removed so sessions are closed after use.
> EIP1-4082 Remove SFTP session caching

- src/main/kotlin/uk/gov/dluhc/printapi/service/CertificateDataRetentionService.kt
- src/test/kotlin/uk/gov/dluhc/printapi/messaging/ApplicationRemovedMessageListenerTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateDataRetentionServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/CertificateAssert.kt
This PR sets the `finalRetentionRemovalDate` (in addition to the `initialRetentionRemovalDate`) when a VCA application is removed from VCA.
> EIP1-4155 - Set finalRetentionRemovalDate

- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/SourceType.kt
- src/main/kotlin/uk/gov/dluhc/printapi/dto/SourceType.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/SourceTypeMapper.kt
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/ddl/0017_anonymous_elector_document_source_type.xml
- src/main/resources/openapi/PrintAPIs.yaml
- src/main/resources/openapi/sqs/print-api-sqs-messaging.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/SourceTypeMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateAnonymousElectorDocumentIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/GenerateAnonymousElectorDocumentRequestBuilder.kt
This PR adds SourceType.anonymous-elector-document to the print-api-sqs-messaging.yaml spec
> EIP1-3549: EIP1-4173: add SourceType.anonymous-elector-document

- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/AnonymousElectorDocument.kt
- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/Certificate.kt
- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/PrintRequest.kt
- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/TemporaryCertificate.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/CertificateMapper.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/PrintRequestMapper.kt
- src/main/kotlin/uk/gov/dluhc/printapi/messaging/ApplicationRemovedMessageListener.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/PrintFileDetailsFactory.kt
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/ddl/0018_EIP1-4481_alter_photo_location_arn_column_in_tables.xml
- src/test/kotlin/uk/gov/dluhc/printapi/database/repository/CertificateRepositoryIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/logging/CorrelationIdMdcIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/CertificateMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/CertificateToPrintRequestMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/PrintRequestMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/messaging/ProcessPrintRequestBatchMessageListenerIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/messaging/SendApplicationToPrintMessageListenerIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/PrintFileDetailsFactoryTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/CertificateAssert.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/PrintRequestAssert.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/CertificateBuilder.kt
- Enabler for Matt's PR https://github.com/cabinetoffice/eip-ero-print-api/pull/184 
- Moves `photo_location_arn` column from `print_request` table to `certificate` table. All the values are copied over to this new column
- Length is increased from `255` to `1024` as fileName itself could be 255 chars, so if someone adds a fileName more than 255 chars, the s3Arn length won't be enough
New column in `certificate` table
*Before changes*
**Changed applied which removed column from `print_request` table**  
**Changeset**
**Updated index**
*Evidence that scripts and migration ran successfully on populated data*
> EIP1-2479: EIP1:4481: Move photo_location_arn column to parent Certificate entity

- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/migration/0002_EIP1-4616_update_aed_status.xml
This PR follows existing PR https://github.com/cabinetoffice/eip-ero-print-api/pull/188 that sets the document status to PRINTED upon generation.
> EIP1-4574: EIP1:4616: Liquibase scripts to mark all existing AED document status to be PRINTED

- src/main/kotlin/uk/gov/dluhc/printapi/dto/GenerateAnonymousElectorDocumentDto.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/AnonymousElectorDocumentMapper.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/aed/AnonymousElectorDocumentService.kt
- src/main/resources/openapi/PrintAPIs.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/AnonymousElectorDocumentMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateAnonymousElectorDocumentIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/dto/GenerateAnonymousElectorDocumentDtoBuilder.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/GenerateAnonymousElectorDocumentRequestBuilder.kt
This needs to be merged just in time when vca [PR](https://github.com/cabinetoffice/eip-ero-voter-card-applications-api/pull/575)  is approved and ready to be merged
> EIP1-4574: EIP1:4666: Rename address fields in print-api spec

- src/main/kotlin/uk/gov/dluhc/printapi/client/ElectoralRegistrationOfficeManagementApiClient.kt
- src/main/kotlin/uk/gov/dluhc/printapi/config/CorrelationIdMdcConfiguration.kt
- src/main/kotlin/uk/gov/dluhc/printapi/config/WebClientConfiguration.kt
- src/main/resources/openapi/PrintAPIs.yaml
- src/main/resources/openapi/sqs/print-api-sqs-messaging.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/logging/CorrelationIdMdcIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/WiremockService.kt
- Ensure correlation id is also returned in HTTP response
- Ensure correlation id is carried through in WebClient requests or Webclient is able to generate a new one.
> EIP1-4653 enhance correlation id

- src/main/kotlin/uk/gov/dluhc/printapi/exception/GlobalExceptionHandler.kt
- src/main/resources/openapi/PrintAPIs.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/rest/DeprecatedGetCertificateSummaryByApplicationIdIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateAedExplainerDocumentIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateTemporaryCertificateExplainerDocumentIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GetCertificateSummaryByApplicationIdIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/assertj/assertions/models/ErrorResponseAssert.kt
This PR updates the openAPI spec and various implementations to make the declaration of REST API error statuses and the implementation consistent (consistent both in terms of a consistent API, and also consistent with VCA in respect of implementation)
> EIP1-4953 - Consistent use of ErrorResponse

- src/main/kotlin/uk/gov/dluhc/printapi/config/CorrelationIdMdcConfiguration.kt
- src/test/kotlin/uk/gov/dluhc/printapi/logging/CorrelationIdMdcIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/logging/TestRestController.kt
This PR adds `CorrelationIdRestTemplateClientHttpRequestInterceptor` that can be used with `RestTemplate`; and also updates the integration tests so that the config class and its tests can be used "outside" of print-api (ie. so that we can move it into a shared library)
(not all the tests have been abstracted from print-api - still need to do the tests for the SQS listener and senders, and the scheduled jobs - we can look to do these another time)
> EIP1-5159 - Added CorrelationIdRestTemplateClientHttpRequestInterceptor

- src/main/resources/application.yml
- src/test/kotlin/uk/gov/dluhc/printapi/config/LocalStackContainerConfiguration.kt
- src/test/kotlin/uk/gov/dluhc/printapi/logging/CorrelationIdMdcIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/logging/TestScheduledJob.kt
- src/test/kotlin/uk/gov/dluhc/printapi/logging/TestSqsListener.kt
Refactored CorrelationIdMdcIntegrationTest so it is abstracted away from any print-api specific implementations
This means it will be much easier to pull out into the other API repos, and then into a shared library as and when we get there
> EIP1-5311 - Refactored CorrelationIdMdcIntegrationTest

- src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/GetAnonymousElectorDocumentsByApplicationIdIntegrationTest.kt
This PR adds an integration test to ensure an empty collection is returned if there are no AEDs for an applicationId.
> Feature/EIP1-5662 Test for no results

- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/AnonymousElectorDocumentSummary.kt
- src/main/kotlin/uk/gov/dluhc/printapi/database/repository/AnonymousElectorDocumentSummaryRepository.kt
- src/main/kotlin/uk/gov/dluhc/printapi/dto/aed/AnonymousSearchSummaryDto.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/aed/AnonymousSearchSummaryMapper.kt
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/ddl/0026_update_aed_summary_view.xml
- src/main/resources/db/changelog/ddl/0027_update_aed_summary_view.xml
- src/test/kotlin/uk/gov/dluhc/printapi/config/IntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/database/repository/AnonymousElectorDocumentSummaryRepositoryIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/aed/AnonymousSearchSummaryMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/DataBuilder.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/dto/aed/AnonymousSearchSummaryDtoBuilder.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/AnonymousElectorDocumentSummaryBuilder.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/AedSummaryBuilder.kt
- New view updated to include `id` of `anonymous_elector_document` entity
- Added repository and it's int test
- Added mapper that will be used by service and controller in subsequent PRs
> EIP1:5626: Summary view repository and mappers + Liquibase 

- src/main/kotlin/uk/gov/dluhc/printapi/dto/CertificateDelivery.kt
- src/main/resources/openapi/PrintAPIs.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/aed/GenerateAnonymousElectorDocumentMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/GenerateAnonymousElectorDocumentIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/dto/CertificateDeliveryDtoBuilder.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/CertificateDeliveryApiBuilder.kt
This PR persists the reason the elector gave for having to collect their AED (if applicable).
> Feature/EIP1-5685 Persist collection reason

- src/main/kotlin/uk/gov/dluhc/printapi/mapper/aed/ReIssueAnonymousElectorDocumentMapper.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/aed/AnonymousElectorDocumentService.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/aed/ReIssueAnonymousElectorDocumentMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/ReIssueAnonymousElectorDocumentIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/aed/AnonymousElectorDocumentServiceTest.kt
This PR adds in the mappings for `electoralRollNumber`, `userId` and `deliveryAddressType` when re-issuing an AED
(because I forgot about them in my earlier PR! 🙄 )
> EIP1-5615 / EIP1-5658 - Added mappings for electoralRollNumber, userId, deliveryAddressType

- src/main/kotlin/uk/gov/dluhc/printapi/rest/aed/AnonymousElectorDocumentPhotoController.kt
- src/main/resources/openapi/PrintAPIs.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/GetAnonymousElectorDocumentsPhotoByApplicationIdIntegrationTest.kt
This PR defines the openAPI spec request for getting the presigned URL for the AED photo. It also implements the basic controller method and usual 401/403/404 integration tests
> EIP1-5820 / EIP1-5836 - Swagger spec and initial controller for getting AED photo

- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/AedContactDetails.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/aed/ReIssueAnonymousElectorDocumentMapper.kt
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/ddl/0028_alter_aed_contact_details_add_last_updated.xml
- src/test/kotlin/uk/gov/dluhc/printapi/database/repository/AnonymousElectorDocumentRepositoryIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/aed/ReIssueAnonymousElectorDocumentMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/JwtAuthenticationTokenBuilder.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/AnonymousElectorDocumentBuilder.kt
This PR adds updatedDate and updatedBy to the AED Contact Details table.
This is to support EIP1-5616 which is to allow the ERO to update the email and/or phoneNumber of an AED (which is the AED Contact Details table).
Without this change it would mean we would lose (overwrite) the createdDate and createdBy fields, thereby losing the history of change
The `print-api` database does not use envers audit tables as it was never intended that database records would ever be updated (by an ERO)
This is a better/faster/pragmatic solution over and above introducing envers at this stage.
> EIP1-5616 / EIP1-5761 - Add updatedDate and updatedBy to AED Contact Details

- README.md
- src/main/kotlin/uk/gov/dluhc/printapi/factory/UrlFactory.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/aed/AnonymousElectorDocumentMapper.kt
- src/main/kotlin/uk/gov/dluhc/printapi/rest/aed/AnonymousElectorDocumentController.kt
- src/main/resources/application.yml
- src/main/resources/openapi/PrintAPIs.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/factory/UrlFactoryTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/aed/AnonymousElectorDocumentMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/GetAnonymousElectorDocumentsByApplicationIdIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/AnonymousElectorDocumentBuilder.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/zip/PhotoLocationBuilder.kt
- src/test/resources/application-integration-test.yml
This PR changes the `AnonymousElectorDocument` response changing the field `photoLocation` to `photoUrl`, with the value being the print-api REST API endpoint to get the photo's presigned URL
This approach, terminology etc is in keeping with how we do it in VCA
> EIP1-5820 / EIP1-5837 - Return photoUrl instead of photoLocation

- README.md
- src/main/kotlin/uk/gov/dluhc/printapi/config/S3Configuration.kt
- src/main/kotlin/uk/gov/dluhc/printapi/rest/aed/AnonymousElectorDocumentPhotoController.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/S3PhotoService.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/aed/AnonymousElectorDocumentService.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/GetAnonymousElectorDocumentsPhotoByApplicationIdIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/S3PhotoServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/S3Utils.kt
- src/test/resources/application-integration-test.yml
This PR completes the endpoint to generate a pre-signed URL to an AED's photo in S3.
I'm not completely sure about the path to retrieve the URL (personally I'm leaning towards `/eros/{eroId}/anonymous-elector-documents/{certificateNumber}/photo`), but this is something @NathanRussellValtech and I have agreed to put aside for the time being and first make sure this works.
> EIP1-5838 - Service to create a pre-signed URL to retrieve an AED photo

- src/main/kotlin/uk/gov/dluhc/printapi/database/repository/AnonymousElectorDocumentSummaryRepository.kt
- src/main/kotlin/uk/gov/dluhc/printapi/database/repository/AnonymousElectorDocumentSummarySpecificationBuilder.kt
- src/main/kotlin/uk/gov/dluhc/printapi/dto/aed/AnonymousSearchCriteriaDto.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/aed/AnonymousElectorDocumentSearchService.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/aed/SearchDataSanitization.kt
- src/test/kotlin/uk/gov/dluhc/printapi/database/repository/AnonymousElectorDocumentSummarySpecificationBuilderIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/aed/SearchDataSanitizationTest.kt
This PR introduces `AnonymousElectorDocumentSummarySpecificationBuilder` as part of being able to support searching for AEDs by application reference 
At the moment it's not wired into the service etc, so as not to risk the release next week and today's COB code cut off etc
The integration test is a temporary test, and will be removed/refactored when we wire the specification builder into the service etc next week
> EIP1-5612 / EIP1-5856 - Introduced AnonymousElectorDocumentSummarySpecificationBuilder

- src/main/kotlin/uk/gov/dluhc/printapi/dto/aed/UpdateAnonymousElectorDocumentDto.kt
- src/main/kotlin/uk/gov/dluhc/printapi/exception/GlobalExceptionHandler.kt
- src/main/kotlin/uk/gov/dluhc/printapi/exception/UpdateAnonymousElectorDocumentValidationException.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/aed/UpdateAnonymousElectorDocumentMapper.kt
- src/main/kotlin/uk/gov/dluhc/printapi/rest/aed/AnonymousElectorDocumentController.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/aed/AnonymousElectorDocumentService.kt
- src/main/resources/openapi/PrintAPIs.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/aed/UpdateAnonymousElectorDocumentMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/UpdateAnonymousElectorDocumentByApplicationIdIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/aed/AnonymousElectorDocumentServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/RandomUtils.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/dto/aed/UpdateAnonymousElectorDocumentDtoBuilder.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/UpdateAnonymousElectorDocumentRequestBuilder.kt
This PR introduces a new endpoint to update the contact details of one or more AEDs, belonging to an application.
I've merged these PRs into this one:
* https://github.com/cabinetoffice/eip-ero-print-api/pull/276
* https://github.com/cabinetoffice/eip-ero-print-api/pull/273
**Endpoint definition**
**Schema**
> EIP1-5918 - New endpoint to update AED contact details

- src/main/resources/openapi/PrintAPIs.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/aed/AedSearchQueryStringParametersMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/AedSearchByParametersAreValidConstraintValidatorTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/SearchAedSummariesIntegrationTest.kt
This PR builds upon (and targets) my [previous PR](https://github.com/cabinetoffice/eip-ero-print-api/pull/275) which added the wired in the specificationBuilder into the AED search service.
When that PR is merged to eip-main, this one can be re-targetted to eip-main
---
This PR updates the openAPI spec to support searching for AEDs by application reference; and a couple of tests to prove.
> EIP1-5612 / EIP1-5857 - openAPI updated to support searchBy applicationReference

- src/main/kotlin/uk/gov/dluhc/printapi/messaging/service/EmailService.kt
- src/main/resources/email-templates/non-prod/certificate-returned.html
- src/main/resources/email-templates/prod/certificate-returned.html
- src/test/kotlin/uk/gov/dluhc/printapi/service/EmailServiceTest.kt
This will change the links in emails for both certificate-returned and certificate-failed-to-print emails - I assume both are supposed to have the application id rather than the application reference? The ticket only mentions the certificate returned case but the links are the same in both cases.
It also adds the application reference into the body of the certificate-returned email. The application reference was already in the email subject, and in the body of the certificate-failed-to-print email.
> EROPSPT-123: Change link in emails to use id instead of reference

- build.gradle.kts
- owasp.suppressions.xml
I grouped the results from the scanner into different types:
- Reported vulnerabilities that I believed were exploitable (this category was empty)
- Reported vulnerabilities that would be fixed by the pending Spring Boot 3 upgrade (these are suppressed with a note explaining so)
- Reported vulnerabilities that could be fixed with no risk to the application (these have been fixed)
- Reported vulnerabilities that would induce some amount of risk in fixing (these have been suppressed until immediately after elections, to be revisited at that time)
> EROPSPT-187 - Update suppressions after latest vuln scan

- .github/workflows/build-and-push.yml
- .github/workflows/build-and-test.yml
- .github/workflows/build-tagged-version-and-push-to-ecr.yml
This can be useful to deploy a version somewhere for testing, without merging it to main or creating a hotfix branch.
Copied from dwp services.
> EROPSPT-None: Add build and push dispatchable workflow

- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/ddl/0030_add_index_for_source_reference_to_certificate_and_temporary_certificate.xml
I suspect this may be the source of the high ACU on the print api tables - the stats endpoints regularly fetches by source reference and source type (without gss code), but the index on the print api table is on (gss_code, source_type, source_reference).
> EROPSPT-None: Add index on source reference to certificate and temporary certificate tables

- src/main/kotlin/uk/gov/dluhc/printapi/exception/GlobalExceptionHandler.kt
- src/main/kotlin/uk/gov/dluhc/printapi/exception/ResponseFileTooLargeException.kt
- src/main/kotlin/uk/gov/dluhc/printapi/rest/TemporaryCertificateController.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/S3PhotoService.kt
- src/main/resources/openapi/PrintAPIs.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/rest/GenerateTemporaryCertificateIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/GenerateTemporaryCertificateRequestBuilder.kt
I don't know if either or both these changes would be worth doing or would be likely to be approved for release:
- Not returning anything more than 9MB should stop VAC from getting stuck hopefully - this seems sensible
- Uploading any temporary certificates that are too big to S3 would make it much easier for us to access them - we'd want to revert this change after Enhanced Support ends and clear out this folder in S3. This seems more risky and would require giving print api write permissions to the bucket, but derisks having to send temporary certificates over until Thursday - otherwise I'm not sure whether we'll be able to keep up with the workload.
> EROPSPT-336: Return error and upload response to S3 when temporary VAC too large

- src/main/kotlin/uk/gov/dluhc/printapi/rest/TemporaryCertificateController.kt
- src/main/resources/application.yml
- src/test/resources/application-integration-test.yml
This was added over the final few days before the general election, to make it easy to retrieve any certificates affected by this issue.
In the short term, it is unlikely that many temporary certificates will be generated after the election, and turning this off means we don't need to remember to manually ensure the data is not retained for longer than it should be. We have a workaround for generating and retrieving a certificate if required, even if this feature is turned off.
In the longer term, we are looking for improvements to ensure large Temporary Certificates can be downloaded.
After releasing this change, we should check the temporary_certificates folder in the live-vca-api-vca-target-bucket is empty, and remove any PDFs in this folder.
> EROPSPT-335: Turn off storing temporary certificates in S3

- src/main/kotlin/uk/gov/dluhc/printapi/mapper/aed/ReIssueAnonymousElectorDocumentMapper.kt
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/aed/ReIssueAnonymousElectorDocumentMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/ReIssueAnonymousElectorDocumentIntegrationTest.kt
I haven't covered the final data retention date here, only the initial date.
~Having had a call with policy, it is no longer clear whether this date should be reset, so I've made the PR into a draft and will hold off merging until we have more clarity.~
Following further calls with policy, we will be going ahead with this change.
> EROPSPT-396: Reset initial removal date when reissuing AED

- src/main/kotlin/uk/gov/dluhc/printapi/database/repository/AnonymousElectorDocumentRepository.kt
- src/main/kotlin/uk/gov/dluhc/printapi/rest/aed/AnonymousElectorDocumentController.kt
- src/main/kotlin/uk/gov/dluhc/printapi/rest/aed/AnonymousElectorDocumentPhotoController.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/aed/AnonymousElectorDocumentService.kt
- src/test/kotlin/uk/gov/dluhc/printapi/config/IntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/GetAnonymousElectorDocumentsByApplicationIdIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/GetAnonymousElectorDocumentsPhotoByApplicationIdIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/ReIssueAnonymousElectorDocumentIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/UpdateAnonymousElectorDocumentByApplicationIdIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/aed/AnonymousElectorDocumentServiceTest.kt
At present, AEDs past the initial data retention will show up on the GetAnonymousElectorDocument endpoint, but will cause errors as some of the fields are null. We can either exclude them from such endpoints or allow these fields to be null - excluding them is likely to be the simpler solution.
This is required now because if there are multiple reissues of a certificate, and some have been through initial data retention while others haven't, then currently attempting to view the AED on the Manage AEDs tab will cause an error.
This change also excludes AEDs that have been through initial data retention from being updated by the update endpoints, which is important as they could add back contact details that was deleted during initial data retention.
These AEDs are also excluded from the …
> EROPSPT-405: Exclude AEDs from endpoints once past initial data retention

- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/Certificate.kt
- src/main/kotlin/uk/gov/dluhc/printapi/messaging/ProcessPrintRequestBatchMessageListener.kt
- src/main/kotlin/uk/gov/dluhc/printapi/messaging/ProcessPrintResponseFileMessageListener.kt
- src/main/kotlin/uk/gov/dluhc/printapi/messaging/ProcessPrintResponseMessageListener.kt
- src/main/kotlin/uk/gov/dluhc/printapi/messaging/service/PrintResponseFileService.kt
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/ddl/0031_EIP1-11169_add_is_from_applications_api_to_certificate.xml
- src/main/resources/openapi/sqs/print-api-sqs-messaging.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/CertificateMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/messaging/ProcessPrintRequestBatchMessageListenerIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/messaging/ProcessPrintResponseFileMessageListenerIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/messaging/ProcessPrintResponseMessageListenerIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/CertificateBuilder.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/messaging/model/ProcessPrintRequestBatchMessageBuilder.kt
Update the Print API to persist whether a certificate was generated for an application in the applications API or VAC.
Update the batch job to use that flag to pick the right statistics queue
Remove the isApplicationsApi flag from internal messages where it's unused.
https://dluhcdigital.atlassian.net/browse/EIP1-11169
> EIP1-11169 store is from applications api on certificate in database

- .github/workflows/build-and-test.yml
- .github/workflows/owasp-dependency-check.yml
- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/AnonymousElectorDocumentSummary.kt
- src/main/kotlin/uk/gov/dluhc/printapi/dto/aed/AnonymousSearchSummaryResults.kt
- src/main/kotlin/uk/gov/dluhc/printapi/mapper/aed/AnonymousSearchSummaryMapper.kt
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/ddl/0032_EROPSPT-397_update_aed_summary_view_include_aeds_after_15_months.xml
- src/main/resources/openapi/PrintAPIs.yaml
- src/test/kotlin/uk/gov/dluhc/printapi/mapper/aed/AnonymousSearchSummaryMapperTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/rest/aed/SearchAedSummariesIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/dto/aed/AnonymousSearchSummaryDtoBuilder.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/entity/AnonymousElectorDocumentSummaryBuilder.kt
- src/test/kotlin/uk/gov/dluhc/printapi/testsupport/testdata/model/AedSummaryBuilder.kt
To keep the PR small-ish, I'm splitting the changes up into multiple PRs. This one is for returning AEDs that have had their first retention period data removed when searched, i.e., showing it in the "Manage AEDs" page.
There will need to be changes to the UI as well, and further changes to the backend for the page that shows individual applications.
https://mhclgdigital.atlassian.net/browse/EROPSPT-397
> EROPSPT-397: Return AEDs post-initial retention period for AED search endpoint

- build.gradle.kts
- owasp.suppressions.xml
Upgrading to SB 3.4.5 resolves CVE-2025-22235 and CVE-2025-22234. It also resolve the dependency clash with dependency-checker 12.1.1, which fixes bugs present in older versions of the dependency checker.
> EROPSPT-443: Upgrade SB to 3.4.5 and dependency checker to 12.1.1, add suppression for CVE-2025-3588

- src/main/kotlin/uk/gov/dluhc/printapi/config/DataRetentionConfiguration.kt
- src/main/kotlin/uk/gov/dluhc/printapi/database/entity/Certificate.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/CertificateDataRetentionService.kt
- src/main/kotlin/uk/gov/dluhc/printapi/service/ElectorDocumentRemovalDateResolver.kt
- src/main/resources/application.yml
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/ddl/0038_EROPSPT-514_remove-temporary-certificate-printer-provided-flag.xml
- src/test/kotlin/uk/gov/dluhc/printapi/service/CertificateDataRetentionServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/printapi/service/ElectorDocumentRemovalDateResolverTest.kt
It's been more than 29 working days (and even more than that by the time we release this) since we released the VAC destruction work so the legacy 28 + 1 working day data retention period is now obsolete, since now VACs created before the change will be immediately delete when their source application gets deleted.
- Can leave tags as tbd until merged
> EROPSPT-514: Remove code for legacy data retention period
